// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvworrfcloehmeopvzdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2d29ycmZjbG9laG1lb3B2emR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NzcxNjIsImV4cCI6MjA2ODA1MzE2Mn0.L6L67IEkZ3eJyfw5kgmfXDTkQUvuKobOT8WZYqt7SPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});